name: Build snapcast

on:
  pull_request:

jobs:
  build:
    # strategy:
    #     matrix:
    #       config: []

    runs-on: ubuntu-latest
    container:
        image: espressif/idf:v5.1.1
        # volumes:
        #   - ${{ github.workspace }}:/project
        #   - /dev:/dev
        # options: --workdir /project
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    # - run: |
    #     . $IDF_PATH/export.sh 
        
    #     for config in 'hifi-esparagus' 'loud-esparagus' 'louder-esparagus'; do
    #         echo Building $config

    #         cp sdkconfig.$config sdkconfig
    #         idf.py build
            
    #         cp build/snapclient.bin ./docs/artifacts/$config-snapclient-latest-snapclient.bin
    #         cp build/storage.bin ./docs/artifacts/$config-snapclient-latest-storage.bin
    #         cp build/ota_data_initial.bin ./docs/artifacts/$config-snapclient-latest-ota_data_initial.bin
    #         cp build/bootloader/bootloader.bin ./docs/artifacts/$config-snapclient-latest-bootloader.bin
    #         cp build/partition_table/partition-table.bin ./docs/artifacts/$config-snapclient-latest-partition-table.bin
    #     done 

    - run: echo $(date) > ./docs/artifacts/testfile.txt
    
    - run: |
        git config --global --add safe.directory /__w/esparagus-snapclient/esparagus-snapclient
    
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com

    #     git status

    # - run: |
    #       git pull
    #       git add .
    #       git commit -m "Commit binaries"
    #       git push
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'Latest binaries by github-actions'
        add: './docs/artifacts'
        fetch: false