name: Build snapcast

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: espressif/idf:v5.1.1
        # volumes:
        #   - ${{ github.workspace }}:/project
        #   - /dev:/dev
        # options: --workdir /project
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - run: . $IDF_PATH/export.sh
    - run: cp sdkconfig.hifi-esparagus sdkconfig
    - run: idf.py build
    - run: ls -al build 
    
    